# Generated by Django 5.2.7 on 2026-03-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_terminal', models.BooleanField(default=True, help_text='Marca si es una terminal principal')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='routes/'),
        ),
    ]
