# Generated by Django 5.1 on 2026-04-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_route_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitud para Google Maps', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitud para Google Maps', null=True),
        ),
    ]
